### ISSUE TITLE
'HOUR_AM' was not declared in this scope

### ISSUE THREAD

**Issue by mahmood-ul-hassan** [stm32duino/STM32RTC#13]
cant find any solution of this problem

> ..\Arduino\libraries\STM32RTC\src/STM32RTC.h:66:10: error: 'HOUR_AM' was not declared in this scope

     AM = HOUR_AM,

          ^~~~~~~

..\Arduino\libraries\STM32RTC\src/STM32RTC.h:67:10: error: 'HOUR_PM' was not declared in this scope

     PM = HOUR_PM

**Comment by fpistm** [comment]
Hi @mahmood-ul-hassan 
You used the master of this library which required the master of the core.
See #12

**Comment by mahmood-ul-hassan** [comment]
yes i used the master
thanks for the help :+1:
