### ISSUE TITLE
 #include "stm32_def.h"                        ^ compilation terminated.

### ISSUE THREAD

**Issue by eklavyainfo** [stm32duino/STM32RTC#43]
compile error

**Comment by fpistm** [comment]
No compile error. Probably you used the master which is not compatible with latest core version.
Or you didn't use the correct STM32 core.
Hard to tell without more info.

**Comment by eklavyainfo** [comment]
i am using stm32f103c8 in arduino ide

**Comment by eklavyainfo** [comment]
#include "stm32_def.h"
                       ^
compilation terminated.
exit status 1
Error compiling for board Generic STM32F103C6/fake STM32F103C8.

**Comment by fpistm** [comment]
So you used Roger Clark core's:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/boards.txt#L437

This library is not for this core but this one:
https://github.com/stm32duino/Arduino_Core_STM32
