### ISSUE TITLE
F401CCU6 BOARD FREEZES WHEN rtc.setClockSource(STM32RTC::LSE_CLOCK); IS CALLED

### ISSUE THREAD

**Issue by augustinenwafor1997** [stm32duino/STM32RTC#65]
I have seen other issues about this but no definitive solution so I decided to create a new issue because this is a serious problem for me. My code works perfectly with the bluepill but once I connect the blackpill, the code doesn't get past the line rtc.setClockSource(STM32RTC::LSE_CLOCK);. Please how do I solve this problem?

**Comment by fpistm** [comment]
Hi @augustinenwafor1997 
Please avoid to create multiple issue for the same things. https://github.com/stm32duino/Arduino_Core_STM32/issues/1698
