### ISSUE TITLE
There is a bug  about alarm interrupt  in V1.3 

### ISSUE THREAD

**Issue by KiraVerSace** [stm32duino/STM32RTC#69]
The same environment one use the STM32RTC V1.2 one use V1.3, but the alarm interrupt is not worked in the V1.3 ,but I do not know why, I use the Stm32l476rct6

```
void rtcAlramInterruptInit(voidFuncPtr funPtr)
{
	uint8_t minutes = rtc.getMinutes();

	minutes = 1 + minutes;	// minutes = (5 - (minutes % 5)) + minutes;
	if(minutes == 60)
	{
		minutes = 0;
	}
	rtc.attachInterrupt(funPtr);
	rtc.setAlarmMinutes(minutes);
	rtc.setAlarmSeconds(0);
	rtc.enableAlarm(rtc.MATCH_MMSS);

	logInfo("RTC Alarm first Interrupt Minutes at [%02d]", minutes);
} 
```

**Comment by ABOSTM** [comment]
Hi @KiraVerSace 
your problem may be similar to https://github.com/stm32duino/STM32LowPower/issues/71https://github.com/stm32duino/STM32LowPower/issues/71
for witch I proposed a fix:
https://github.com/stm32duino/STM32RTC/pull/68
You may have a try
