### ISSUE TITLE
Examples rtc alarm with interrupt not working

### ISSUE THREAD

**Issue by rozrabiak** [stm32duino/STM32RTC#70]
Examples provided with library not working with stm32f401 (blackpill).
Interrupt time never start.
I try to change time in examples - no effects..
Vscode, platformio, stm32core 14.0.1 for arduino

**Comment by jan019** [comment]
Try calling `rtc.setPrediv(-1, -1);` before the `rtc.begin() ` function. Also see https://github.com/stm32duino/STM32RTC/issues/71.

**Comment by rozrabiak** [comment]
> Try calling `rtc.setPrediv(-1, -1);` before the `rtc.begin() ` function. Also see #71.

It work's, thank's!
