### ISSUE TITLE
Compiled binary bloat

### ISSUE THREAD

**Issue by bondus** [stm32duino/STM32RTC#73]
I tried to use this library but had to stop since even a basic test project does not fit the 32kb flash of my chip.

One culprit is the call to gmtime() that pulls in large parts of libgcc and libc, exception handling and other stuff. It helps a bit to change it to gmtime_r(). 

Fixing that something still pulls in some kind of unwinding from libgcc bloating the compiled binary.

**Comment by tshcherban** [comment]
@bondus depends on what features do you use. You can try manipulating dateTime manually, like this:
```
  // SET
  rtc.setDate(1, 1, 1);
  rtc.setTime(0, 0, 0);
  rtc.setAlarmDate(1, 1, 1);
  rtc.setAlarmTime(0, 0, 3);
  rtc.enableAlarm(STM32RTC::Alarm_Match::MATCH_SS);

  // GET
  uint8_t year, month, day, weekDay;
  rtc.getDate(&weekDay, &day, &month, &year);

  uint8_t hours, minutes, seconds;
  uint32_t subSeconds;
  rtc.getTime(&hours, &minutes, &seconds, &subSeconds);
```
it fits in 14kb and not calls `gmtime`/`mktime` internally, saving lots of flash.
