### ISSUE TITLE
Broken alarm functionality?

### ISSUE THREAD

**Issue by tshcherban** [stm32duino/STM32RTC#76]
There is a [LowPower](https://github.com/stm32duino/STM32LowPower/issues/79) library, which uses this one. After [PR#67](https://github.com/stm32duino/STM32RTC/pull/67) into STM32RTC some functionality stopped working (waking up by rtc alarm).
Here's [original issue](https://github.com/stm32duino/STM32LowPower/issues/79).
Problem occurs on software reset, on cold CPU boot all works as expected. Maybe some initialization missed/redundant?

**Comment by ABOSTM** [comment]
Let's keep only the original issue from STM32LowPower library
