### ISSUE TITLE
DWM1000 STM32F103

### ISSUE THREAD

**Issue by hhl-16** [stm32duino/STM32RTC#81]
hi guys
i use https://github.com/thotro/arduino-dw1000 to stm32 connect  dwm1000. it works
I'm running a test sketch basicsender with frequency 3hz ~ T =  300ms
I am using a battery for the circuit, so I want to use it
#include "STM32LowPower.h"
 but error
<img width="775" alt="image" src="https://user-images.githubusercontent.com/84115903/206677526-1453c689-1aec-422b-9333-55288180c7ee.png">

**Comment by fpistm** [comment]
Hi,

avoid to open several entries for the same issues.
I close this one as you open it in STM32RTC while you talk about STM32LowPower and it is a duplicated of this discussion:
https://github.com/stm32duino/Arduino_Core_STM32/discussions/1894
