### ISSUE TITLE
getTime/setTime

### ISSUE THREAD

**Issue by fralbo** [stm32duino/STM32RTC#99]
Hello,
That's maybe a pity that getTime/setTime are not implemented as usual.
Because of this, we cannot use the https://github.com/ag88/stm32duino_rtcadj library which could be very interesting.

**Comment by fralbo** [comment]
sorry no real standard implementation..

**Comment by fpistm** [comment]
As stated:

> This Arduino sketch is built based on Stm32duino libmaple core

So not compatible with the STM32 core.

**Comment by fralbo** [comment]
Ok sorry, thanks a lot.

Le sam. 16 sept. 2023 à 16:09, Frederic Pillon ***@***.***> a
écrit :
